version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_password_segura
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
