import Link from "next/link";
import Tag from "@/components/ui/Tag";
import { BackLink, DisabledAction } from "../_ui";

export default async function CampaignDetailPage({ params }: { params: Promise<{ campaignId: string }> }) {
  const { campaignId } = await params;
  const campaignName = campaignId === "fauna-urbana" ? "Fauna urbana en parques" : campaignId === "huertos-comunitarios" ? "Huertos comunitarios" : "Ruido nocturno en el centro";

  return <div className="mx-auto max-w-4xl"><BackLink href="/supervision">Volver a supervisar</BackLink><div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.12em] text-accent">Detalle de campaña</p><h1 className="mt-2 text-2xl font-extrabold text-ink">{campaignName}</h1><p className="mt-1 text-[13px] text-ink-2">Salud urbana · creada por Luis Márquez · meta 300 aportes</p></div><div className="flex flex-wrap gap-2"><DisabledAction tone="danger">Rechazar</DisabledAction><DisabledAction>Reportar</DisabledAction><DisabledAction tone="primary">Aceptar campaña</DisabledAction></div></div><div className="mb-5 rounded-lg border border-line bg-sunken p-4 text-[13px] text-ink-2">Vista de maqueta: las acciones de moderación se conectarán más adelante. Puedes navegar por el flujo de consulta de participantes y el panel.</div><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><p className="text-[13.5px] leading-6 text-ink-2">Registro de niveles de ruido nocturno en zonas habitacionales cercanas a bares y avenidas con alto tránsito, con evidencia y descripción del punto.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="space-y-3"><div className="flex justify-between border-b border-line pb-3 text-[13px]"><span className="text-ink-2">Estado</span><Tag tone="warn">En revisión</Tag></div><div className="flex justify-between border-b border-line pb-3 text-[13px]"><span className="text-ink-2">Tipo de aporte</span><span>Audio y texto</span></div></div><div className="space-y-3"><div className="flex justify-between border-b border-line pb-3 text-[13px]"><span className="text-ink-2">Enviada</span><span className="font-mono">hace 44 h</span></div><div className="flex justify-between border-b border-line pb-3 text-[13px]"><span className="text-ink-2">Vigencia</span><span className="font-mono">hasta 30 sep</span></div></div></div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/supervision/${campaignId}/usuarios`} className="rounded-pill bg-accent px-4 py-2 text-[12.5px] font-bold text-white">Ver usuarios de la campaña</Link><Link href={`/supervision/${campaignId}/panel`} className="rounded-pill border border-line-2 px-4 py-2 text-[12.5px] font-bold text-ink-2">Abrir panel</Link></div></section></div>;
}
