import Tag from "@/components/ui/Tag";
import { BackLink, DisabledAction } from "../../../../_ui";

const contributions = [["Aporte #4821", "Aceptado", "Árbol de laurel de la India en la banqueta de av. Insurgentes, aparentemente sano, con alcorque descubierto.", "14 ago · 10:32", "Foto", "3.2 MB", "ok"], ["Aporte #4903", "En revisión", "Palma seca frente a la escuela primaria de la colonia Centro.", "15 ago · 08:12", "Foto", "2.7 MB", "warn"], ["Aporte #4744", "Aceptado", "Ficus de gran porte en el camellón de av. Insurgentes, con raíces levantando la banqueta.", "11 ago · 17:40", "Foto", "2.9 MB", "ok"]] as const;

export default async function UserContributionsPage({ params }: { params: Promise<{ campaignId: string; userId: string }> }) {
  const { campaignId, userId } = await params;
  const participant = userId === "mara" ? "Mara Ortiz" : userId === "ana" ? "Ana Ruiz" : "Diego Salas";
  return <div className="mx-auto max-w-4xl"><BackLink href={`/supervision/${campaignId}/usuarios`}>Volver a usuarios</BackLink><div className="mb-5 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.12em] text-accent">Aportes de participante</p><h1 className="mt-2 text-2xl font-extrabold text-ink">{participant}</h1><p className="mt-1 text-[13px] text-ink-2">Aportes en “Censo de árboles urbanos”</p></div><DisabledAction tone="danger">Banear a {participant.split(" ")[0]}</DisabledAction></div><div className="mb-5 rounded-lg border border-line bg-sunken p-4 text-[13px] text-ink-2">Vista de solo lectura: puedes consultar estos aportes, pero no aprobarlos, rechazarlos ni eliminarlos desde aquí.</div><div className="space-y-3">{contributions.map(([title, status, description, submitted, type, size, tone]) => <article key={title} className="rounded-lg border border-line bg-surface p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-[15px] font-extrabold text-ink">{title}</h2><p className="mt-2 max-w-2xl text-[13px] leading-6 text-ink-2">{description}</p></div><Tag tone={tone}>{status}</Tag></div><div className="mt-4 grid gap-3 border-t border-line pt-4 text-[12px] sm:grid-cols-3"><p><span className="text-ink-3">Enviado</span><br /><span className="font-mono text-ink-2">{submitted}</span></p><p><span className="text-ink-3">Tipo</span><br /><span className="text-ink-2">{type}</span></p><p><span className="text-ink-3">Peso</span><br /><span className="font-mono text-ink-2">{size}</span></p></div></article>)}</div></div>;
}
