import Tag from "@/components/ui/Tag";
import { BackLink } from "../../_ui";

const metrics = [["Aportes aprobados", "310"], ["Participantes", "86"], ["Pendientes", "18"], ["Meta", "62%"]] as const;
const bars = [30, 40, 52, 46, 66, 82, 75, 60, 70, 86, 96, 80, 91, 104];

export default function SupervisedCampaignPanel() {

  return <div className="mx-auto max-w-5xl"><BackLink href="/supervision/campanas">Volver a campañas supervisadas</BackLink><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.12em] text-accent">Panel de campaña</p><h1 className="mt-2 text-2xl font-extrabold text-ink">Censo de árboles urbanos</h1><p className="mt-1 font-mono text-[12px] text-ink-2">1 ago – 12 sep 2026 · activa</p></div><Tag tone="ok">En vivo · actualiza cada 3 s</Tag></div><div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <section key={label} className="rounded-lg border border-line bg-surface p-5 shadow-sm"><p className="text-[12.5px] text-ink-2">{label}</p><p className="mt-2 text-3xl font-extrabold tracking-tight text-ink">{value}</p></section>)}</div><section className="mb-6 rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="text-[13px] font-bold text-ink">Recolección diaria</h2><div className="mt-5 flex h-36 items-end gap-2 border-b border-line px-1">{bars.map((height, index) => <div key={index} className="flex-1 rounded-t bg-accent" style={{ height }} title={`${index + 1} de agosto`} />)}</div><div className="mt-2 flex justify-between font-mono text-[10px] text-ink-3"><span>1 ago</span><span>14 ago</span></div></section><div className="grid gap-5 md:grid-cols-2"><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="text-[13px] font-bold text-ink">Por tipo de dato</h2><div className="mt-5 space-y-4"><MetricBar label="Foto" value="211" width="92%" /><MetricBar label="Texto" value="18" width="8%" /></div></section><section className="rounded-lg border border-line bg-surface p-5 shadow-sm"><h2 className="text-[13px] font-bold text-ink">Progreso hacia la meta</h2><div className="mt-5 h-2.5 overflow-hidden rounded-pill bg-sunken"><div className="h-full w-[62%] rounded-pill bg-ok" /></div><div className="mt-2 flex justify-between font-mono text-[11px] text-ink-3"><span>310 de 500 aportes</span><span>29 días restantes</span></div><p className="mt-5 rounded-lg bg-sunken p-4 text-[12.5px] leading-5 text-ink-2">Al ritmo actual de 22 aportes por día, la meta se alcanza alrededor del 24 de agosto.</p></section></div></div>;
}

function MetricBar({ label, value, width }: { label: string; value: string; width: string }) {
  return <div className="flex items-center gap-3 text-[12.5px]"><span className="w-12 text-ink-2">{label}</span><div className="h-2 flex-1 overflow-hidden rounded-pill bg-sunken"><div className="h-full rounded-pill bg-ok" style={{ width }} /></div><span className="w-8 text-right font-mono text-ink-2">{value}</span></div>;
}
