import Link from "next/link";
import { BackLink } from "../../_ui";

const users = [["diego", "Diego Salas", "diego@correo.com", "6", "hace 3 h"], ["mara", "Mara Ortiz", "mara@correo.com", "4", "hace 9 h"], ["ana", "Ana Ruiz", "ana@correo.com", "2", "hace 1 d"]] as const;

export default async function CampaignUsersPage({ params }: { params: Promise<{ campaignId: string }> }) {
  const { campaignId } = await params;
  return <div className="mx-auto max-w-5xl"><BackLink href="/supervision/campanas">Volver a campañas supervisadas</BackLink><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.12em] text-accent">Participantes</p><h1 className="mt-2 text-2xl font-extrabold text-ink">Usuarios · Censo de árboles urbanos</h1><p className="mt-1 text-[13px] text-ink-2">12 colaboradores con al menos un aporte</p></div><span className="rounded-pill border border-line-2 bg-surface px-4 py-2 text-[12.5px] text-ink-3">Buscar usuario</span></div><div className="overflow-x-auto rounded-lg border border-line bg-surface p-5 shadow-sm"><table className="w-full min-w-[650px] text-left text-[13px]"><thead className="border-b border-line font-mono text-[10px] uppercase tracking-[0.1em] text-ink-3"><tr><th className="pb-3 font-medium">Usuario</th><th className="pb-3 font-medium">Aportes</th><th className="pb-3 font-medium">Último aporte</th><th className="pb-3" /></tr></thead><tbody>{users.map(([id, name, email, count, last]) => <tr key={id} className="border-b border-line last:border-0"><td className="py-4"><p className="font-bold text-ink">{name}</p><p className="font-mono text-[11px] text-ink-3">{email}</p></td><td className="font-mono">{count}</td><td className="font-mono text-[12px] text-ink-3">{last}</td><td className="text-right"><Link href={`/supervision/${campaignId}/usuarios/${id}/aportes`} className="rounded-pill border border-line-2 px-3 py-1.5 text-[12px] font-bold text-ink-2 hover:border-accent">Ver aportes</Link></td></tr>)}</tbody></table></div><div className="mt-5 rounded-lg border border-line bg-sunken p-4 text-[13px] text-ink-2">Como supervisor puedes consultar la participación. Las acciones de baneo se agregarán cuando se conecte la lógica.</div></div>;
}
